name: Deploy NuGet(OTAPI3)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build -c Release
          dotnet pack -c Release -o nupkgs
      # Publish to nuget
      - name: Push TShockAPI
        run: |
          dotnet nuget push nupkgs/UnrealMultiple.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
